### ISSUE TITLE
[TASK] Refactor category system

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_event_mgt#312]
Refactor the category system, so it uses the category system included in TYPO3 

- [x] Refactoring of code to work with sys_categories instead of local categories #314 
- [x] Refactoring of TYPO3 backend forms to accept sys_categories #314 
- [x] Refactoring of frontend output of categories including limitation to selected storage page #314 
- [x] ~~Limitation option to only show a subset of available sys_categories~~
- [x] Migration wizard for existing users #313 
- [x] Update of Unit and Functional tests #314 
- [x] Update of documentation #316
